name: Run test
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
     - name: Run tests
       env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}       
       run: 
          python app.py
