name: Run test
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
     - name: Run tests
       env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}       
       run: |
         echo: $SECRET_KEY 
